#!/bin/bash

# CachyOS Hello Script
# Installs cachyos-hello with paru
# Usage: ./hellohooks

set -e

GREEN='\033[0;32m'
NC='\033[0m'

print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

main() {
    print_status "Installing cachyos-hello with paru..."
    
    # Install cachyos-hello package
    paru -S --needed --noconfirm cachyos-hello
    
    print_status "cachyos-hello installation complete!"
}

main "$@"