#!/usr/bin/env python3
"""
Epub Renamer - Simple, fast epub file renamer
Format: title - author.epub

Usage:
    python3 epub_renamer.py file.epub
    curl -L https://raw.githubusercontent.com/user/repo/main/epub_renamer.py | python3 - file.epub

Author: Generated by opencode
License: MIT
"""

import argparse
import os
import sys
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path


class EpubRenamer:
    """Simple epub file renamer using standard library only."""

    def __init__(self):
        self.namespaces = {
            'dc': 'http://purl.org/dc/elements/1.1/',
            'opf': 'http://www.idpf.org/2007/opf'
        }

    def extract_metadata(self, epub_path):
        """Extract title and author from epub metadata."""
        try:
            with zipfile.ZipFile(epub_path, 'r') as zf:
                # Find container.xml
                container_info = zf.getinfo('META-INF/container.xml')
                container_xml = zf.read(container_info)

                # Parse container to find content.opf
                root = ET.fromstring(container_xml)
                rootfile_elem = root.find('.//{urn:oasis:names:tc:opendocument:xmlns:container}rootfile')
                if rootfile_elem is None:
                    raise ValueError("Could not find rootfile in container.xml")

                opf_path = rootfile_elem.get('full-path')
                if not opf_path:
                    raise ValueError("Rootfile element missing full-path attribute")

                # Read and parse content.opf
                opf_info = zf.getinfo(opf_path)
                opf_xml = zf.read(opf_info)

                # Extract metadata
                opf_root = ET.fromstring(opf_xml)
                metadata = opf_root.find('.//{http://www.idpf.org/2007/opf}metadata')

                title = self._get_text(metadata, './/dc:title')
                author = self._get_text(metadata, './/dc:creator')

                return title, author

        except Exception as e:
            print(f"Error reading epub metadata: {e}", file=sys.stderr)
            return None, None

    def _get_text(self, element, xpath):
        """Safely extract text from XML element."""
        try:
            found = element.find(xpath, self.namespaces)
            return found.text.strip() if found is not None and found.text else None
        except:
            return None

    def sanitize_filename(self, text):
        """Sanitize text for use in filenames."""
        if not text:
            return "Unknown"

        # Replace invalid characters
        invalid_chars = '<>:"/\\|?*'
        for char in invalid_chars:
            text = text.replace(char, '_')

        # Remove control characters and normalize whitespace
        text = ''.join(c for c in text if ord(c) >= 32)
        text = ' '.join(text.split())

        # Limit length
        return text[:100] if len(text) > 100 else text

    def generate_new_filename(self, title, author, original_path):
        """Generate new filename in format: title - author.epub"""
        title_clean = self.sanitize_filename(title)
        author_clean = self.sanitize_filename(author)

        # Handle missing metadata
        if not title_clean or title_clean == "Unknown":
            title_clean = "Unknown Title"
        if not author_clean or author_clean == "Unknown":
            author_clean = "Unknown Author"

        return f"{title_clean} - {author_clean}.epub"

    def rename_file(self, epub_path, new_name):
        """Safely rename the epub file."""
        epub_path = Path(epub_path)
        new_path = epub_path.parent / new_name

        # Check if target already exists
        if new_path.exists():
            print(f"Warning: {new_path} already exists, skipping", file=sys.stderr)
            return False

        try:
            epub_path.rename(new_path)
            print(f"Renamed: {epub_path} -> {new_path}")
            return True
        except Exception as e:
            print(f"Error renaming file: {e}", file=sys.stderr)
            return False

    def process_file(self, epub_path):
        """Process a single epub file."""
        if not Path(epub_path).exists():
            print(f"Error: File not found: {epub_path}", file=sys.stderr)
            return False

        if not epub_path.lower().endswith('.epub'):
            print(f"Error: Not an epub file: {epub_path}", file=sys.stderr)
            return False

        print(f"Processing: {epub_path}")

        title, author = self.extract_metadata(epub_path)
        if not title and not author:
            print("Warning: Could not extract metadata, using filename as fallback", file=sys.stderr)
            # Fallback: try to extract from filename
            filename = Path(epub_path).stem
            if ' - ' in filename:
                parts = filename.split(' - ', 1)
                title = parts[0]
                author = parts[1] if len(parts) > 1 else None

        new_name = self.generate_new_filename(title, author, epub_path)
        return self.rename_file(epub_path, new_name)


def main():
    parser = argparse.ArgumentParser(
        description='Rename epub files to "title - author.epub" format',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 epub_renamer.py book.epub
  curl -L https://raw.githubusercontent.com/user/repo/main/epub_renamer.py | python3 - book.epub
        """
    )
    parser.add_argument('files', nargs='+', help='Epub files to rename')
    parser.add_argument('--dry-run', action='store_true', help='Show what would be renamed without actually doing it')

    args = parser.parse_args()

    renamer = EpubRenamer()
    success_count = 0

    for epub_file in args.files:
        try:
            if args.dry_run:
                title, author = renamer.extract_metadata(epub_file)
                new_name = renamer.generate_new_filename(title, author, epub_file)
                print(f"Would rename: {epub_file} -> {new_name}")
                success_count += 1
            else:
                if renamer.process_file(epub_file):
                    success_count += 1
        except Exception as e:
            print(f"Error processing {epub_file}: {e}", file=sys.stderr)

    print(f"\nProcessed {success_count}/{len(args.files)} files successfully")
    return 0 if success_count == len(args.files) else 1


if __name__ == '__main__':
    sys.exit(main())